---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: doyle
  domain: iswhatcddown.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-4fac4133
  image_type: t1.micro
  image_id: ami-3d4ff254
  security_groups:
  - default
  - doyle
  - apache
  - common
  - monit
  - db
  - postgresql
  - postgresql_master
  - passenger
  - web_tools
  external_host: ec2-184-73-90-49.compute-1.amazonaws.com
  external_ip: 184.73.90.49
  internal_host: domU-12-31-39-0F-D4-73.compute-1.internal
  internal_ip: 10.193.215.129
  zone: us-east-1a
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
