app_name: doyle
app_user: app
admin_email: "karl@karlbright.org"
web_port: 80
web_tools_port: 8001
web_tools_user: admin
web_tools_password: captainDoyl3
timezone: Australia/Perth
domain: iswhatcddown.com
rubber_secret: "#{File.expand_path('~') + '/.ec2' + (Rubber.env == 'production' ? '' : '_dev') + '/rubber-secret.yml' rescue ''}"

cloud_providers:
  aws:
    region: us-east-1
    image_type: t1.micro
    image_id: ami-2419a74d
cloud_provider: aws

security_groups:
  default:
    description: default group
    rules:
      - protocol: tcp
        from_port: 22
        to_port: 22
        source_ips: [0.0.0.0/0]
  web:
    description: "To open up port #{web_port}/#{web_ssl_port} for http server on web role"
    rules:
      - protocol: tcp
        from_port: "#{web_port}"
        to_port: "#{web_port}"
        source_ips: [0.0.0.0/0]
  web_tools:
    description: "To open up port #{web_tools_port}/#{web_tools_ssl_port} for internal/tools http server"
    rules:
      - protocol: tcp
        from_port: "#{web_tools_port}"
        to_port: "#{web_tools_port}"
        source_ips: [0.0.0.0/0]
assigned_security_groups: [default,web,web_tools]
auto_security_groups: true
isolate_security_groups: false
prompt_for_security_group_sync: true

packages: [postfix, build-essential, git-core, ec2-ami-tools, libxslt-dev, ntp]
gems: [open4, aws-s3, bundler, [rubber, "#{Rubber.version}"]]
stop_on_error_cmd: "function error_exit { exit 99; }; trap error_exit ERR"
