# OPTIONAL: The dns provider to use.  Need to exist in dns_providers below
# dns_provider: nettica

# OPTIONAL: The configuration for each dns provider (nettica|zerigo|dyndns)
#          This lets rubber update a dynamic dns service with the instance alias and ip
#

dns_provider: zerigo

dns_records:
  - host: doyle
    domain: iswhatcddown.com
    data: "#{rubber_instances.for_role('web').first.external_ip}"
    type: A
    ttl: 300

  - host: whatson
    domain: iswhatcddown.com
    data: s3.amazonaws.com
    type: CNAME
    ttl: 300

# OPTIONAL: Lets you configure your dns service, for example to add other CNAMES
#           or setup dns round robin, etc.  Run "cap rubber:setup_dns_records"
#           to apply them as rubber only sets up instance aliases as part of
#           the standard lifecycle
#
#  dns_records:
#    # simple A record
#    - host: bar
#      data: 1.1.1.1
#
#    # more detailed A record
#    - host: bar
#      domain: otherdomain.com
#      data: 1.1.1.1
#      type: A
#      ttl: 300
#
#    # tld A record
#    - host: ''
#      data: 1.1.1.1
#      type: A
#
#    # tld ALIAS record -- Route53 extension to point tld at an Elastic Load Balancer group
#    - host: ''
#      domain: example.com
#      type: A
#      data:
#        hosted_zone_id: XXYYZZ
#        dns_name: my-app-elb-group.us-east-1.elb.amazonaws.com
#
#    # simple CNAME record
#    - host: otherbar
#      domain: foo.com
#      data: bar.foo.com
#      type: CNAME
#      ttl: 300
#
#    # 2 of the same A records is a round robin dns
#    - host: rr
#      domain: foo.com
#      data: 1.1.1.1
#      type: A
#      ttl: 300
#    - host: rr
#      domain: foo.com
#      data: 1.1.1.2
#      type: A
#      ttl: 300
#
#    # A record, grabbing ip from instance config
#    - host: baz
#      domain: foo.com
#      data: "#{rubber_instances.for_role('web').first.external_ip}"
#      type: A
#      ttl: 300
#
#    # MX record
#    - host: ''
#      domain: foo.com
#      data: mail.foo.com
#      type: MX
#      ttl: 300
#      priority: 10

